name: Docker CI + Kubernetes Deploy

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/wisecow-app:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/wisecow-app:latest

    - name: Set up kubectl
      run: |
        echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig
        kubectl config get-contexts

    - name: Deploy to Kubernetes
      run: |
        export KUBECONFIG=$PWD/kubeconfig
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml